In [ ]:
'''Encoding Techniques
       - convert categorical data into numerical data  - Encoder

1. Label Encoding  - Inhertant order . Male, Female - natural order - Male - 1, Female - 0 , ( Order - High School, Bachelor, Master, Phd) - Tree based Models
2. One-Hot Encoding -
3. Ordinal Encoding
4. Target Guided Ordinal Encoding
5. Mean Encoding
6. Binary Encoding
7. Target guided MEan Encoding


'''

In [ ]:
# Label Encoding  - inhertant order . Tree-based   Avoid when Data is nominal

# Customer loyalty levels

from sklearn.preprocessing import LabelEncoder
import pandas as pd

# real world eg : customer loyalty levels

data =pd.DataFrame({'Loyalty':['Silver','Gold','Platinum','Silver','Gold']})
data

label_encoder = LabelEncoder()
data['Loyalty_encoder'] = label_encoder.fit_transform(data['Loyalty'])
data

    Loyalty  Loyalty_encoder
0    Silver                2
1      Gold                0
2  Platinum                1
3    Silver                2
4      Gold                0

In [ ]:
# ordinal Encoding - nominal order, Any Model  Avoid When - No order in data

from sklearn.preprocessing import OrdinalEncoder
import pandas as pd

data=pd.DataFrame({'Education':['High School','Bachelor','Master','PhD','Bachelor']})
data

# define order manually

education_order=['High School','Bachelor','Master','PhD']

ordinal_encoder = OrdinalEncoder(categories=[education_order])

# Fit and Transfrom
data['Education_encoder'] = ordinal_encoder.fit_transform(data[['Education']])
data

     Education  Education_encoder
0  High School                0.0
1     Bachelor                1.0
2       Master                2.0
3          PhD                3.0
4     Bachelor                1.0

In [ ]:
# One Hot Encoding - Nominal Data , extend the features , Linear, Neural Networks, Avoid when - High Cardinality categorical fatures

from sklearn.preprocessing import OneHotEncoder
import pandas as pd

# dataframe - payment method

data=pd.DataFrame({'Payment':['Credit Card','Debit Card','Paypal','Net Banking','Credit Card']})
data

onehot_encoder=OneHotEncoder(sparse_output=False)


# fit and transform

encoded_data=onehot_encoder.fit_transform(data[['Payment']])


# convert back to DataFrame
encoded_df=pd.DataFrame(encoded_data,columns=onehot_encoder.get_feature_names_out(['Payment']))

# concatenate

final_data=pd.concat([data,encoded_df],axis=1)
final_data

       Payment  Payment_Credit Card  ...  Payment_Net Banking  Payment_Paypal
0  Credit Card                  1.0  ...                  0.0             0.0
1   Debit Card                  0.0  ...                  0.0             0.0
2       Paypal                  0.0  ...                  0.0             1.0
3  Net Banking                  0.0  ...                  1.0             0.0
4  Credit Card                  1.0  ...                  0.0             0.0

[5 rows x 5 columns]

In [ ]:
# Frequency encoding - without extending the features,High Cardinality categorical fatures

import pandas as pd

# Product categories in an ecommernce platform - consider more than 100 unique features - don't use one hot encoding

data = pd.DataFrame({
    'product_category':['Electronics','Clothing','Electronics','Home','Clothing','Electronics','Beauty','Home']

})

# frequency encoding
freq_encoding = data['product_category'].value_counts()

# map the frequencies

data['product_Category_Encoded']=data['product_category'].map(freq_encoding)
data

  product_category  product_Category_Encoded
0      Electronics                         3
1         Clothing                         2
2      Electronics                         3
3             Home                         2
4         Clothing                         2
5      Electronics                         3
6           Beauty                         1
7             Home                         2

In [ ]:
# problem statement - titanic survival prediction based on passenger details

# required lib
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,classification_report
import matplotlib.pyplot as plt
import seaborn as sns
import pickle

In [ ]:
# load the dataset
titanic_dataset=pd.read_csv('train.csv')
titanic_dataset

     PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0              1         0       3  ...   7.2500   NaN         S
1              2         1       1  ...  71.2833   C85         C
2              3         1       3  ...   7.9250   NaN         S
3              4         1       1  ...  53.1000  C123         S
4              5         0       3  ...   8.0500   NaN         S
..           ...       ...     ...  ...      ...   ...       ...
886          887         0       2  ...  13.0000   NaN         S
887          888         1       1  ...  30.0000   B42         S
888          889         0       3  ...  23.4500   NaN         S
889          890         1       1  ...  30.0000  C148         C
890          891         0       3  ...   7.7500   NaN         Q

[891 rows x 12 columns]

In [ ]:
# Data Preprocessing
# handle missing values

titanic_dataset.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [ ]:
# fill the missing values
titanic_dataset['Embarked'].fillna(titanic_dataset['Embarked'].mode()[0])

0      S
1      C
2      S
3      S
4      S
      ..
886    S
887    S
888    S
889    C
890    Q
Name: Embarked, Length: 891, dtype: object

In [ ]:
titanic_dataset['Age'].fillna(titanic_dataset['Age'].median(),inplace=True)
titanic_dataset['Embarked'].fillna(titanic_dataset['Embarked'].mode()[0],inplace=True)
titanic_dataset.drop(columns=['Cabin'],inplace=True)

<ipython-input-15-f98811da9de3>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  titanic_dataset['Age'].fillna(titanic_dataset['Age'].median(),inplace=True)
<ipython-input-15-f98811da9de3>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  titanic_dataset['Embarked'].fillna(titanic_dataset['Embarked'].mode()[0],inplace=True)

In [ ]:
titanic_dataset.isna().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [ ]:
# segregate features and target  i.e X and Y

X=titanic_dataset[['Pclass','Sex','Age','SibSp','Parch','Embarked']]
Y=titanic_dataset['Survived']

In [ ]:
# Encoding in X

# Label Encoder

label_encoder=LabelEncoder()
X['Sex']=label_encoder.fit_transform(X['Sex'])

<ipython-input-18-c44ee67efb06>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['Sex']=label_encoder.fit_transform(X['Sex'])

In [ ]:
X

     Pclass  Sex   Age  SibSp  Parch Embarked
0         3    1  22.0      1      0        S
1         1    0  38.0      1      0        C
2         3    0  26.0      0      0        S
3         1    0  35.0      1      0        S
4         3    1  35.0      0      0        S
..      ...  ...   ...    ...    ...      ...
886       2    1  27.0      0      0        S
887       1    0  19.0      0      0        S
888       3    0  28.0      1      2        S
889       1    1  26.0      0      0        C
890       3    1  32.0      0      0        Q

[891 rows x 6 columns]

In [ ]:
X=pd.get_dummies(X,columns=['Embarked'],prefix='Embarked')

In [ ]:
X

     Pclass  Sex   Age  SibSp  Parch  Embarked_C  Embarked_Q  Embarked_S
0         3    1  22.0      1      0       False       False        True
1         1    0  38.0      1      0        True       False       False
2         3    0  26.0      0      0       False       False        True
3         1    0  35.0      1      0       False       False        True
4         3    1  35.0      0      0       False       False        True
..      ...  ...   ...    ...    ...         ...         ...         ...
886       2    1  27.0      0      0       False       False        True
887       1    0  19.0      0      0       False       False        True
888       3    0  28.0      1      2       False       False        True
889       1    1  26.0      0      0        True       False       False
890       3    1  32.0      0      0       False        True       False

[891 rows x 8 columns]

In [ ]:
# Spilt traing and test data

X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=42)

In [ ]:
# train the model
model=LogisticRegression(max_iter=200)
model.fit(X_train,Y_train)

LogisticRegression(max_iter=200)

In [ ]:
# save the model

with open('titanic_model.pkl','wb') as model_file:
    pickle.dump(model,model_file)

In [ ]:
# load the model

with open('titanic_model.pkl','rb') as model_file:
    loaded_model=pickle.load(model_file)
#predict

sample_data=X_test.iloc[0:1]
Prediction=loaded_model.predict(sample_data)
Prediction

array([0])

In [ ]:
# predict the result

accuracy_score=loaded_model.score(X_test,Y_test)
accuracy_score

0.8044692737430168